### ISSUE TITLE
Incendiary trap arrow x is not visible to caster and others using the mod

### ISSUE THREAD

**Issue by Zezo12345** [TerableCoder/show-archer-traps#1]
Tested on Caali proxy

**Comment by Zezo12345** [comment]
Can you update the Skillid for incendiary trap? thanks in advance.

**Comment by TerableCoder** [comment]
I just tested it and it works. You must have another module hiding it.

**Comment by Zezo12345** [comment]
Yes i found the gpk mod which was the culprit. :)
